### ISSUE TITLE
TypeError: Cannot read property 'current' of undefined

### ISSUE THREAD

**Issue by nanbean** [enactjs/cli#215] opened 2020-04-04 22:45 UTC
Test/index.js
```
import React from 'react';
import PropTypes from 'prop-types';

const TestComp = ({value}) => {
        return (
                <div>
                        {value}
                </div>
        );
};

TestComp.propTypes = {
        value: PropTypes.string.isRequired,
};

export default TestComp;

```
----
Test/index.test.js
```
import React from 'react';
import { render } from '@testing-library/react';
import '@testing-library/jest-dom/extend-expect';

import Test from './index';

describe('st Test Cases', () => {
        it('matches snapshot', () => {
                const utils = render(
                        <Test
                                value={'on'}
                        />
                );
                expect(utils.container).toMatchSnapshot();
        });

});

```
I tried in latest cli 2.7.0
my steps..
$ enact create test
$ npm install react react-dom
$ npm install --save-dev @testing-library/jest-dom@testing-library/react
// add upper code(index.js) and test code(index.test.js)

enact test returns below errors
$ enact test

    TypeError: Cannot read property 'current' of undefined

       7 | describe('st Test Cases', () => {
       8 |      it('matches snapshot', () => {
    >  9 |              const utils = render(
         |                            ^
      10 |                      <Test
      11 |                              value={'on'}
      12 |                      />

      at act (../../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:908:55)
      at render (../../../node_modules/@testing-library/react/dist/pure.js:82:26)
      at Object.it (index.test.js:9:17)

this is my package.json
```
        "dependencies": {
                "@enact/core": "^3.0.0",
                "@enact/i18n": "^3.0.0",
                "@enact/moonstone": "^3.0.0",
                "@enact/spotlight": "^3.0.0",
                "@enact/ui": "^3.0.0",
                "ilib": "^14.2.0",
                "prop-types": "^15.6.2",
                "react": "^16.13.1",
                "react-dom": "^16.13.1"
        },
        "devDependencies": {
                "@testing-library/jest-dom": "^5.3.0",
                "@testing-library/react": "^10.0.2"
        }
```

**Comment by nanbean** [comment] 2020-04-04 22:49
> import React, {useCallback, useMemo} from 'react';
> import PropTypes from 'prop-types';
> 
> const TestComp = ({value}) => {
> return (
> 
> {value}
> 
> );
> };
> TestComp.propTypes = {
> value: PropTypes.string.isRequired,
> };
> 
> export default TestComp;
> 
> import React from 'react';
> import { render } from '@testing-library/react';
> import '@testing-library/jest-dom/extend-expect';
> 
> import Test from './index';
> 
> describe('st Test Cases', () => {
> it('matches snapshot', () => {
> const utils = render(
> <Test
> value={'on'}
> />
> );
> expect(utils.container).toMatchSnapshot();
> });
> 
> });
> 
> I tried in latest cli 2.7.0
> enact create test
> npm install react react-dom
> npm install --save-dev @testing-library/jest-dom@testing-library/react
> add upper code and test code
> 
> enact test returns below errors
> 
> ```
> TypeError: Cannot read property 'current' of undefined
> 
>    7 | describe('st Test Cases', () => {
>    8 |      it('matches snapshot', () => {
> >  9 |              const utils = render(
>      |                            ^
>   10 |                      <Test
>   11 |                              value={'on'}
>   12 |                      />
> 
>   at act (../../../node_modules/react-dom/cjs/react-dom-test-utils.development.js:908:55)
>   at render (../../../node_modules/@testing-library/react/dist/pure.js:82:26)
>   at Object.it (index.test.js:9:17)
> ```

**Comment by webOS101** [comment] 2020-04-06 02:13
Unfortunately, I don't have a solution for you yet.  The issue is caused by mismatches in react and testing tools.  The cli uses an older version of `react-test-renderer`, for one thing.  For another, it's likely that multiple instances of react are being loaded during the test build.  We have special webpack rules to prevent this when using the cli's testing tools but this external library is probably not taking advantage of this.  I'm sure @JayCanuck will have some better ideas.

**Comment by JayCanuck** [comment] 2020-08-11 17:04
@nanbean this should be fixed as of the latest Enact CLI 3.x release. Feel free to create a followup issue if it (or other issues) occur again.

**Closed by JayCanuck** 2020-08-11 17:04 UTC
